/** Markets (countries) with DataForSEO location codes. `iso` uses "UK" for the United Kingdom like DataForSEO. */
export type Country = { iso: string; name: string; locationCode: number; language: string; languages: string[]; googleAdsOnly: boolean };

export const COUNTRIES: Country[] = [
  { iso: "AL", name: "Albania", locationCode: 2008, language: "sq", languages: ["sq"], googleAdsOnly: false },
  { iso: "DZ", name: "Algeria", locationCode: 2012, language: "fr", languages: ["ar", "fr"], googleAdsOnly: false },
  { iso: "AD", name: "Andorra", locationCode: 2020, language: "ca", languages: ["ca"], googleAdsOnly: true },
  { iso: "AO", name: "Angola", locationCode: 2024, language: "pt", languages: ["pt"], googleAdsOnly: false },
  { iso: "AR", name: "Argentina", locationCode: 2032, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "AM", name: "Armenia", locationCode: 2051, language: "hy", languages: ["hy"], googleAdsOnly: false },
  { iso: "AU", name: "Australia", locationCode: 2036, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "AT", name: "Austria", locationCode: 2040, language: "de", languages: ["de"], googleAdsOnly: false },
  { iso: "AZ", name: "Azerbaijan", locationCode: 2031, language: "az", languages: ["az"], googleAdsOnly: false },
  { iso: "BS", name: "Bahamas", locationCode: 2044, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "BH", name: "Bahrain", locationCode: 2048, language: "ar", languages: ["ar"], googleAdsOnly: false },
  { iso: "BD", name: "Bangladesh", locationCode: 2050, language: "bn", languages: ["bn"], googleAdsOnly: false },
  { iso: "BB", name: "Barbados", locationCode: 2052, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "BE", name: "Belgium", locationCode: 2056, language: "nl", languages: ["de", "fr", "nl"], googleAdsOnly: false },
  { iso: "BZ", name: "Belize", locationCode: 2084, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "BO", name: "Bolivia", locationCode: 2068, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "BA", name: "Bosnia and Herzegovina", locationCode: 2070, language: "bs", languages: ["bs"], googleAdsOnly: false },
  { iso: "BW", name: "Botswana", locationCode: 2072, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "BR", name: "Brazil", locationCode: 2076, language: "pt", languages: ["pt"], googleAdsOnly: false },
  { iso: "BN", name: "Brunei", locationCode: 2096, language: "ms", languages: ["ms"], googleAdsOnly: true },
  { iso: "BG", name: "Bulgaria", locationCode: 2100, language: "bg", languages: ["bg"], googleAdsOnly: false },
  { iso: "BF", name: "Burkina Faso", locationCode: 2854, language: "fr", languages: ["fr"], googleAdsOnly: false },
  { iso: "KH", name: "Cambodia", locationCode: 2116, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "CM", name: "Cameroon", locationCode: 2120, language: "fr", languages: ["fr"], googleAdsOnly: false },
  { iso: "CA", name: "Canada", locationCode: 2124, language: "en", languages: ["en", "fr"], googleAdsOnly: false },
  { iso: "CL", name: "Chile", locationCode: 2152, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "CO", name: "Colombia", locationCode: 2170, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "CR", name: "Costa Rica", locationCode: 2188, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "HR", name: "Croatia", locationCode: 2191, language: "hr", languages: ["hr"], googleAdsOnly: false },
  { iso: "CY", name: "Cyprus", locationCode: 2196, language: "el", languages: ["el", "en"], googleAdsOnly: false },
  { iso: "CZ", name: "Czechia", locationCode: 2203, language: "cs", languages: ["cs"], googleAdsOnly: false },
  { iso: "CI", name: "Côte d'Ivoire", locationCode: 2384, language: "fr", languages: ["fr"], googleAdsOnly: false },
  { iso: "DK", name: "Denmark", locationCode: 2208, language: "da", languages: ["da"], googleAdsOnly: false },
  { iso: "DO", name: "Dominican Republic", locationCode: 2214, language: "es", languages: ["es"], googleAdsOnly: true },
  { iso: "EC", name: "Ecuador", locationCode: 2218, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "EG", name: "Egypt", locationCode: 2818, language: "ar", languages: ["ar", "en"], googleAdsOnly: false },
  { iso: "SV", name: "El Salvador", locationCode: 2222, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "EE", name: "Estonia", locationCode: 2233, language: "et", languages: ["et"], googleAdsOnly: false },
  { iso: "ET", name: "Ethiopia", locationCode: 2231, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "FJ", name: "Fiji", locationCode: 2242, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "FI", name: "Finland", locationCode: 2246, language: "fi", languages: ["fi"], googleAdsOnly: false },
  { iso: "FR", name: "France", locationCode: 2250, language: "fr", languages: ["fr"], googleAdsOnly: false },
  { iso: "GE", name: "Georgia", locationCode: 2268, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "DE", name: "Germany", locationCode: 2276, language: "de", languages: ["de"], googleAdsOnly: false },
  { iso: "GH", name: "Ghana", locationCode: 2288, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "GR", name: "Greece", locationCode: 2300, language: "el", languages: ["el", "en"], googleAdsOnly: false },
  { iso: "GT", name: "Guatemala", locationCode: 2320, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "GG", name: "Guernsey", locationCode: 2831, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "GY", name: "Guyana", locationCode: 2328, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "HT", name: "Haiti", locationCode: 2332, language: "fr", languages: ["fr"], googleAdsOnly: true },
  { iso: "HN", name: "Honduras", locationCode: 2340, language: "es", languages: ["es"], googleAdsOnly: true },
  { iso: "HK", name: "Hong Kong", locationCode: 2344, language: "zh-TW", languages: ["en", "zh-TW"], googleAdsOnly: false },
  { iso: "HU", name: "Hungary", locationCode: 2348, language: "hu", languages: ["hu"], googleAdsOnly: false },
  { iso: "IS", name: "Iceland", locationCode: 2352, language: "is", languages: ["is"], googleAdsOnly: true },
  { iso: "IN", name: "India", locationCode: 2356, language: "en", languages: ["en", "hi"], googleAdsOnly: false },
  { iso: "ID", name: "Indonesia", locationCode: 2360, language: "id", languages: ["en", "id"], googleAdsOnly: false },
  { iso: "IQ", name: "Iraq", locationCode: 2368, language: "ar", languages: ["ar"], googleAdsOnly: true },
  { iso: "IE", name: "Ireland", locationCode: 2372, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "IM", name: "Isle of Man", locationCode: 2833, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "IL", name: "Israel", locationCode: 2376, language: "he", languages: ["ar", "he"], googleAdsOnly: false },
  { iso: "IT", name: "Italy", locationCode: 2380, language: "it", languages: ["it"], googleAdsOnly: false },
  { iso: "JM", name: "Jamaica", locationCode: 2388, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "JP", name: "Japan", locationCode: 2392, language: "ja", languages: ["ja"], googleAdsOnly: false },
  { iso: "JE", name: "Jersey", locationCode: 2832, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "JO", name: "Jordan", locationCode: 2400, language: "ar", languages: ["ar"], googleAdsOnly: false },
  { iso: "KZ", name: "Kazakhstan", locationCode: 2398, language: "ru", languages: ["ru"], googleAdsOnly: false },
  { iso: "KE", name: "Kenya", locationCode: 2404, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "KW", name: "Kuwait", locationCode: 2414, language: "ar", languages: ["ar"], googleAdsOnly: true },
  { iso: "KG", name: "Kyrgyzstan", locationCode: 2417, language: "ru", languages: ["ru"], googleAdsOnly: true },
  { iso: "LA", name: "Laos", locationCode: 2418, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "LV", name: "Latvia", locationCode: 2428, language: "lv", languages: ["lv"], googleAdsOnly: false },
  { iso: "LB", name: "Lebanon", locationCode: 2422, language: "ar", languages: ["ar"], googleAdsOnly: true },
  { iso: "LI", name: "Liechtenstein", locationCode: 2438, language: "de", languages: ["de"], googleAdsOnly: true },
  { iso: "LT", name: "Lithuania", locationCode: 2440, language: "lt", languages: ["lt"], googleAdsOnly: false },
  { iso: "LU", name: "Luxembourg", locationCode: 2442, language: "fr", languages: ["fr"], googleAdsOnly: true },
  { iso: "MG", name: "Madagascar", locationCode: 2450, language: "fr", languages: ["fr"], googleAdsOnly: true },
  { iso: "MW", name: "Malawi", locationCode: 2454, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "MY", name: "Malaysia", locationCode: 2458, language: "en", languages: ["en", "ms"], googleAdsOnly: false },
  { iso: "MV", name: "Maldives", locationCode: 2462, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "MT", name: "Malta", locationCode: 2470, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "MU", name: "Mauritius", locationCode: 2480, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "MX", name: "Mexico", locationCode: 2484, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "MD", name: "Moldova", locationCode: 2498, language: "ro", languages: ["ro"], googleAdsOnly: false },
  { iso: "MC", name: "Monaco", locationCode: 2492, language: "fr", languages: ["fr"], googleAdsOnly: false },
  { iso: "MN", name: "Mongolia", locationCode: 2496, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "ME", name: "Montenegro", locationCode: 2499, language: "sr", languages: ["sr"], googleAdsOnly: true },
  { iso: "MA", name: "Morocco", locationCode: 2504, language: "ar", languages: ["ar", "fr"], googleAdsOnly: false },
  { iso: "MZ", name: "Mozambique", locationCode: 2508, language: "pt", languages: ["pt"], googleAdsOnly: true },
  { iso: "MM", name: "Myanmar", locationCode: 2104, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "NA", name: "Namibia", locationCode: 2516, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "NP", name: "Nepal", locationCode: 2524, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "NL", name: "Netherlands", locationCode: 2528, language: "nl", languages: ["nl"], googleAdsOnly: false },
  { iso: "NZ", name: "New Zealand", locationCode: 2554, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "NI", name: "Nicaragua", locationCode: 2558, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "NG", name: "Nigeria", locationCode: 2566, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "MK", name: "North Macedonia", locationCode: 2807, language: "mk", languages: ["mk"], googleAdsOnly: false },
  { iso: "NO", name: "Norway", locationCode: 2578, language: "nb", languages: ["nb"], googleAdsOnly: false },
  { iso: "OM", name: "Oman", locationCode: 2512, language: "ar", languages: ["ar"], googleAdsOnly: true },
  { iso: "PK", name: "Pakistan", locationCode: 2586, language: "en", languages: ["en", "ur"], googleAdsOnly: false },
  { iso: "PS", name: "Palestine", locationCode: 2275, language: "ar", languages: ["ar"], googleAdsOnly: true },
  { iso: "PA", name: "Panama", locationCode: 2591, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "PG", name: "Papua New Guinea", locationCode: 2598, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "PY", name: "Paraguay", locationCode: 2600, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "PE", name: "Peru", locationCode: 2604, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "PH", name: "Philippines", locationCode: 2608, language: "en", languages: ["en", "tl"], googleAdsOnly: false },
  { iso: "PL", name: "Poland", locationCode: 2616, language: "pl", languages: ["pl"], googleAdsOnly: false },
  { iso: "PT", name: "Portugal", locationCode: 2620, language: "pt", languages: ["pt"], googleAdsOnly: false },
  { iso: "QA", name: "Qatar", locationCode: 2634, language: "ar", languages: ["ar"], googleAdsOnly: true },
  { iso: "RO", name: "Romania", locationCode: 2642, language: "ro", languages: ["ro"], googleAdsOnly: false },
  { iso: "RW", name: "Rwanda", locationCode: 2646, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "SM", name: "San Marino", locationCode: 2674, language: "it", languages: ["it"], googleAdsOnly: true },
  { iso: "SA", name: "Saudi Arabia", locationCode: 2682, language: "ar", languages: ["ar"], googleAdsOnly: false },
  { iso: "SN", name: "Senegal", locationCode: 2686, language: "fr", languages: ["fr"], googleAdsOnly: false },
  { iso: "RS", name: "Serbia", locationCode: 2688, language: "sr", languages: ["sr"], googleAdsOnly: false },
  { iso: "SG", name: "Singapore", locationCode: 2702, language: "en", languages: ["en", "zh-CN"], googleAdsOnly: false },
  { iso: "SK", name: "Slovakia", locationCode: 2703, language: "sk", languages: ["sk"], googleAdsOnly: false },
  { iso: "SI", name: "Slovenia", locationCode: 2705, language: "sl", languages: ["sl"], googleAdsOnly: false },
  { iso: "ZA", name: "South Africa", locationCode: 2710, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "KR", name: "South Korea", locationCode: 2410, language: "ko", languages: ["ko"], googleAdsOnly: false },
  { iso: "ES", name: "Spain", locationCode: 2724, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "LK", name: "Sri Lanka", locationCode: 2144, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "SR", name: "Suriname", locationCode: 2740, language: "nl", languages: ["nl"], googleAdsOnly: true },
  { iso: "SE", name: "Sweden", locationCode: 2752, language: "sv", languages: ["sv"], googleAdsOnly: false },
  { iso: "CH", name: "Switzerland", locationCode: 2756, language: "de", languages: ["de", "fr", "it"], googleAdsOnly: false },
  { iso: "TW", name: "Taiwan", locationCode: 2158, language: "zh-TW", languages: ["zh-TW"], googleAdsOnly: false },
  { iso: "TJ", name: "Tajikistan", locationCode: 2762, language: "ru", languages: ["ru"], googleAdsOnly: true },
  { iso: "TZ", name: "Tanzania", locationCode: 2834, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "TH", name: "Thailand", locationCode: 2764, language: "th", languages: ["th"], googleAdsOnly: false },
  { iso: "TT", name: "Trinidad and Tobago", locationCode: 2780, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "TN", name: "Tunisia", locationCode: 2788, language: "ar", languages: ["ar"], googleAdsOnly: false },
  { iso: "TR", name: "Turkey", locationCode: 2792, language: "tr", languages: ["tr"], googleAdsOnly: false },
  { iso: "TM", name: "Turkmenistan", locationCode: 2795, language: "ru", languages: ["ru"], googleAdsOnly: true },
  { iso: "UG", name: "Uganda", locationCode: 2800, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "UA", name: "Ukraine", locationCode: 2804, language: "uk", languages: ["ru", "uk"], googleAdsOnly: false },
  { iso: "AE", name: "United Arab Emirates", locationCode: 2784, language: "en", languages: ["ar", "en"], googleAdsOnly: false },
  { iso: "UK", name: "United Kingdom", locationCode: 2826, language: "en", languages: ["en"], googleAdsOnly: false },
  { iso: "US", name: "United States", locationCode: 2840, language: "en", languages: ["en", "es"], googleAdsOnly: false },
  { iso: "UY", name: "Uruguay", locationCode: 2858, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "UZ", name: "Uzbekistan", locationCode: 2860, language: "ru", languages: ["ru"], googleAdsOnly: true },
  { iso: "VE", name: "Venezuela", locationCode: 2862, language: "es", languages: ["es"], googleAdsOnly: false },
  { iso: "VN", name: "Vietnam", locationCode: 2704, language: "vi", languages: ["en", "vi"], googleAdsOnly: false },
  { iso: "ZM", name: "Zambia", locationCode: 2894, language: "en", languages: ["en"], googleAdsOnly: true },
  { iso: "ZW", name: "Zimbabwe", locationCode: 2716, language: "en", languages: ["en"], googleAdsOnly: true },
];

const byIso = new Map(COUNTRIES.map((c) => [c.iso, c]));
const byCode = new Map(COUNTRIES.map((c) => [c.locationCode, c]));

/** Accepts "GB" as alias for "UK". */
export function getCountry(iso: string | null | undefined): Country | undefined {
  if (!iso) return undefined;
  const key = iso.toUpperCase() === "GB" ? "UK" : iso.toUpperCase();
  return byIso.get(key);
}

export function getCountryByLocationCode(code: number | null | undefined): Country | undefined {
  return code == null ? undefined : byCode.get(code);
}

/** Emoji flag for an ISO-3166 alpha-2 code ("UK" → 🇬🇧). */
export function flagEmoji(iso: string | null | undefined): string {
  if (!iso) return "🌐";
  const code = iso.toUpperCase() === "UK" ? "GB" : iso.toUpperCase();
  if (!/^[A-Z]{2}$/.test(code)) return "🌐";
  return String.fromCodePoint(...[...code].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
}

export const LABS_COUNTRIES = COUNTRIES.filter((c) => !c.googleAdsOnly);
export const DEFAULT_COUNTRY = "US";

export const LANGUAGES: { code: string; name: string }[] = [
  { code: "en", name: "English" }, { code: "de", name: "German" }, { code: "fr", name: "French" },
  { code: "es", name: "Spanish" }, { code: "it", name: "Italian" }, { code: "nl", name: "Dutch" },
  { code: "pt", name: "Portuguese" }, { code: "pl", name: "Polish" }, { code: "sv", name: "Swedish" },
  { code: "da", name: "Danish" }, { code: "nb", name: "Norwegian" }, { code: "fi", name: "Finnish" },
  { code: "cs", name: "Czech" }, { code: "sk", name: "Slovak" }, { code: "hu", name: "Hungarian" },
  { code: "ro", name: "Romanian" }, { code: "bg", name: "Bulgarian" }, { code: "el", name: "Greek" },
  { code: "tr", name: "Turkish" }, { code: "ru", name: "Russian" }, { code: "uk", name: "Ukrainian" },
  { code: "ar", name: "Arabic" }, { code: "he", name: "Hebrew" }, { code: "hi", name: "Hindi" },
  { code: "ja", name: "Japanese" }, { code: "ko", name: "Korean" }, { code: "zh-CN", name: "Chinese (Simplified)" },
  { code: "zh-TW", name: "Chinese (Traditional)" }, { code: "th", name: "Thai" }, { code: "vi", name: "Vietnamese" },
  { code: "id", name: "Indonesian" }, { code: "ms", name: "Malay" }, { code: "tl", name: "Filipino" },
  { code: "hr", name: "Croatian" }, { code: "sr", name: "Serbian" }, { code: "sl", name: "Slovenian" },
  { code: "et", name: "Estonian" }, { code: "lv", name: "Latvian" }, { code: "lt", name: "Lithuanian" },
  { code: "sq", name: "Albanian" }, { code: "hy", name: "Armenian" }, { code: "az", name: "Azerbaijani" },
  { code: "bn", name: "Bengali" }, { code: "bs", name: "Bosnian" }, { code: "mk", name: "Macedonian" },
  { code: "ur", name: "Urdu" }, { code: "ca", name: "Catalan" }, { code: "is", name: "Icelandic" },
];
