version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: "/cloud"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - cloud

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependencies
      - ci

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependencies
      - docker
