"use server";

import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/server/db/client";
import { jobs } from "@/server/db/schema";
import { actionProject, ActionError, runAction } from "@/server/auth/guards";
import { logAudit } from "@/server/audit";
import { enqueueJob } from "@/server/jobs/queue";
import { createList, deleteItems, deleteList, ensureDefaultList, getListRow, renameList, setDefaultList } from "@/server/ai/research/lists";
import { addItemsToTracker } from "@/server/ai/research/tracker";
import { autoGenerateDefaultList, defaultPromptSetConfig, promptSetConfigSchema, startPromptGeneration } from "@/server/ai/research/generate";
import { ENRICH_JOB, importItems, importRowSchema } from "@/server/ai/research/import";
import { availableLlmProviders } from "@/server/ai/llm";
import { isDataForSeoConfigured } from "@/server/dataforseo/client";
import type { JobStatus, PromptSetConfig } from "../types";

/*
 * Permissions (ai-research):
 * - viewing: project access (page guard)
 * - lists, generating, importing, enriching volumes, adding to the tracker: `prompts.manage`
 *   (includes the DataForSEO volume lookups that are part of generation/import)
 */

const listName = z.string().trim().min(1).max(120);

export async function createListAction(projectId: string, name: string) {
  return runAction(async () => {
    const ctx = await actionProject(projectId, "prompts.manage");
    const row = await createList(projectId, listName.parse(name), "manual", ctx.user.id);
    return { id: row.id };
  });
}

export async function renameListAction(projectId: string, listId: string, name: string) {
  return runAction(async () => {
    await actionProject(projectId, "prompts.manage");
    await renameList(projectId, z.string().parse(listId), listName.parse(name));
    return true;
  });
}

export async function setDefaultListAction(projectId: string, listId: string) {
  return runAction(async () => {
    await actionProject(projectId, "prompts.manage");
    await setDefaultList(projectId, z.string().parse(listId));
    return true;
  });
}

export async function deleteListAction(projectId: string, listId: string) {
  return runAction(async () => {
    const ctx = await actionProject(projectId, "prompts.manage");
    await deleteList(projectId, z.string().parse(listId));
    void logAudit("prompt_research.list_deleted", { actor: ctx.user, projectId, targetType: "prompt_research_list", targetId: listId });
    return true;
  });
}

const targetSchema = z.union([z.object({ listId: z.string().min(1) }), z.object({ newListName: listName })]);

async function resolveTarget(projectId: string, target: z.infer<typeof targetSchema>, source: "generated" | "import", userId: string) {
  if ("listId" in target) {
    const row = await getListRow(projectId, target.listId);
    if (!row) throw new ActionError("List not found.", "not_found");
    return row;
  }
  return createList(projectId, target.newListName, source, userId);
}

export async function generatePromptSetAction(projectId: string, target: z.input<typeof targetSchema>, config: PromptSetConfig) {
  return runAction(async () => {
    const ctx = await actionProject(projectId, "prompts.manage");
    const cfg = promptSetConfigSchema.parse(config);
    if (!(await availableLlmProviders()).length)
      throw new ActionError("No AI provider is available. Connect a local agent or add an API key in Admin → AI Providers.", "invalid");
    const list = await resolveTarget(projectId, targetSchema.parse(target), "generated", ctx.user.id);
    const { jobId } = await startPromptGeneration({ projectId, listId: list.id, config: cfg, userId: ctx.user.id });
    void logAudit("prompt_research.generate", { actor: ctx.user, projectId, targetType: "prompt_research_list", targetId: list.id, meta: { count: cfg.count } });
    return { listId: list.id, jobId };
  });
}

/** Called once from the page when the default list is empty (first visit). */
export async function autoGenerateAction(projectId: string) {
  return runAction(async () => {
    const ctx = await actionProject(projectId);
    if (!ctx.permissions.has("prompts.manage")) return { jobId: null };
    if (!(await availableLlmProviders()).length) return { jobId: null };
    const jobId = await autoGenerateDefaultList(projectId, ctx.user.id);
    return { jobId };
  });
}

export async function defaultConfigAction(projectId: string) {
  return runAction(async () => {
    await actionProject(projectId);
    return defaultPromptSetConfig(projectId);
  });
}

export async function importPromptsAction(projectId: string, target: z.input<typeof targetSchema>, rows: z.input<typeof importRowSchema>[]) {
  return runAction(async () => {
    const ctx = await actionProject(projectId, "prompts.manage");
    const parsedRows = z.array(importRowSchema).min(1, "Nothing to import.").max(5000, "At most 5,000 prompts per import.").parse(rows);
    const list = await resolveTarget(projectId, targetSchema.parse(target), "import", ctx.user.id);
    const res = await importItems(projectId, list.id, parsedRows, ctx.user.id);
    void logAudit("prompt_research.import", { actor: ctx.user, projectId, targetType: "prompt_research_list", targetId: list.id, meta: res });
    return { listId: list.id, ...res };
  });
}

export async function addToTrackerAction(projectId: string, itemIds: string[]) {
  return runAction(async () => {
    const ctx = await actionProject(projectId, "prompts.manage");
    const ids = z.array(z.string().min(1)).min(1).max(500).parse(itemIds);
    const res = await addItemsToTracker(projectId, ids, ctx.user.id);
    if (res.added === 0 && res.linked === 0 && res.skippedOverLimit > 0)
      throw new ActionError("Prompt limit reached for this project (Admin → Limits & Budgets).", "conflict");
    return res;
  });
}

export async function deleteItemsAction(projectId: string, itemIds: string[]) {
  return runAction(async () => {
    await actionProject(projectId, "prompts.manage");
    await deleteItems(projectId, z.array(z.string()).max(2000).parse(itemIds));
    return true;
  });
}

export async function refreshVolumesAction(projectId: string, listId: string) {
  return runAction(async () => {
    const ctx = await actionProject(projectId, "prompts.manage");
    const list = await getListRow(projectId, listId);
    if (!list) throw new ActionError("List not found.", "not_found");
    if (!(await isDataForSeoConfigured()) && !(await availableLlmProviders()).length)
      throw new ActionError("Connect DataForSEO (Admin → Data Providers) or an AI provider to estimate volumes.", "invalid");
    const job = await enqueueJob(ENRICH_JOB, { projectId, listId, userId: ctx.user.id }, { projectId, createdBy: ctx.user.id, dedupeKey: `prompt-research-enrich:${listId}`, maxAttempts: 1 });
    return { jobId: job?.id ?? null };
  });
}

export async function ensureDefaultListAction(projectId: string) {
  return runAction(async () => {
    await actionProject(projectId);
    const row = await ensureDefaultList(projectId);
    return { id: row.id };
  });
}

/** Job status for UI polling (only jobs of this project). */
export async function getJobStatusAction(projectId: string, jobId: string) {
  return runAction(async (): Promise<JobStatus | null> => {
    await actionProject(projectId);
    const [row] = await db
      .select({ id: jobs.id, status: jobs.status, progress: jobs.progress, lastError: jobs.lastError })
      .from(jobs)
      .where(and(eq(jobs.id, z.string().parse(jobId)), eq(jobs.projectId, projectId)))
      .limit(1);
    if (!row) return null;
    return { id: row.id, status: row.status, progress: (row.progress as JobStatus["progress"]) ?? null, error: row.lastError };
  });
}
