import {
  BarChart3,
  Bot,
  BookOpen,
  Brain,
  Bug,
  Cpu,
  Euro,
  FileText,
  Gauge,
  GitFork,
  Globe,
  Heart,
  House,
  Key,
  Layers,
  Library,
  LineChart,
  Link2,
  ListChecks,
  Mail,
  MapPin,
  Megaphone,
  Plug,
  Presentation,
  Radar,
  Search,
  SearchCheck,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Swords,
  Tag,
  Terminal,
  Users,
  Wallet,
  WandSparkles,
  type LucideIcon,
} from "lucide-react";
import type { NavIcon as NavIconName } from "@/lib/navigation";

const map: Record<NavIconName, LucideIcon> = {
  home: House,
  sparkles: Sparkles,
  search: Search,
  radar: Radar,
  swords: Swords,
  heart: Heart,
  book: BookOpen,
  "shopping-bag": ShoppingBag,
  megaphone: Megaphone,
  cpu: Cpu,
  "git-fork": GitFork,
  "bar-chart": BarChart3,
  users: Users,
  bot: Bot,
  "search-check": SearchCheck,
  euro: Euro,
  "shield-check": ShieldCheck,
  wand: WandSparkles,
  "list-checks": ListChecks,
  "file-text": FileText,
  bug: Bug,
  presentation: Presentation,
  library: Library,
  key: Key,
  plug: Plug,
  wallet: Wallet,
  settings: Settings,
  "line-chart": LineChart,
  link: Link2,
  globe: Globe,
  "map-pin": MapPin,
  gauge: Gauge,
  tag: Tag,
  terminal: Terminal,
  shield: Shield,
  mail: Mail,
  brain: Brain,
  layers: Layers,
};

export function NavIcon({ name, className }: { name?: NavIconName; className?: string }) {
  if (!name) return null;
  const Icon = map[name];
  return <Icon className={className} />;
}
