import "server-only";
import { S, type OpenApiOperation } from "../openapi-helpers";
import {
  contentDetailQuery,
  contentListQuery,
  findingsQuery,
  generateContentInput,
  optimizeUrlInput,
  runFactCheckInput,
  taskCommentInput,
  taskStatusInput,
} from "../optimize";

const { str, strN, num, int, arr, obj } = S;
const pagination = obj({ page: int, limit: int, total: int, totalPages: int });

const contentItem = obj({
  id: str,
  title: str,
  kind: { type: "string", enum: ["article", "rewrite"] },
  status: str,
  targetPrompt: strN,
  targetKeyword: strN,
  aeoScore: num,
  baselineScore: num,
  wordCount: int,
  publishedUrl: strN,
  sourceUrl: strN,
  generationStage: strN,
  error: strN,
  updatedAt: str,
  createdAt: str,
});

/** REST v1 operations: content, fact check and task updates (optimize module). */
export const optimizeOperations: OpenApiOperation[] = [
  {
    method: "get",
    path: "/projects/{projectId}/content",
    operationId: "listContent",
    summary: "List content",
    description: "AI-optimized articles and page rewrites with AEO score (0–100); `meta.summary` has totals.",
    tag: "Content",
    scope: "read",
    query: contentListQuery,
    data: arr(contentItem),
    meta: { summary: { type: "object" }, pagination },
  },
  {
    method: "post",
    path: "/projects/{projectId}/content",
    operationId: "generateContent",
    summary: "Generate article",
    description: "Writes a new AI-search-optimized article for a target prompt (job, 202). Uses the local agent / AI API — poll GET /content/{contentId}.",
    tag: "Content",
    scope: "write",
    permission: "prompts.manage",
    body: generateContentInput,
    status: 202,
    data: obj({ contentId: str, status: str }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/content/optimize-url",
    operationId: "optimizePageContent",
    summary: "Optimize an existing page",
    description: "Imports a public page, scores it and (with AI) rewrites it into an optimized draft (job, 202). The live page is not changed.",
    tag: "Content",
    scope: "write",
    permission: "prompts.manage",
    body: optimizeUrlInput,
    status: 202,
    data: obj({ contentId: str, status: str, rewrite: { type: "boolean" } }),
  },
  {
    method: "get",
    path: "/projects/{projectId}/content/{contentId}",
    operationId: "getContent",
    summary: "Get content",
    description: "Markdown body, meta, slug, FAQs, entities, citations, JSON-LD and AEO score.",
    tag: "Content",
    scope: "read",
    query: contentDetailQuery,
    data: { type: "object" },
  },
  {
    method: "get",
    path: "/projects/{projectId}/fact-check",
    operationId: "getFactCheckOverview",
    summary: "Fact check overview",
    description: "Label alignment totals (matched, off-label, contradicted, unsupported, outdated, needs review), assets and the last run.",
    tag: "Fact check",
    scope: "read",
    data: obj({ totals: { type: "object" }, lastCheckedAt: strN, answersTracked: int, aiReady: { type: "boolean" }, run: { type: "object" }, assets: arr({ type: "object" }) }),
  },
  {
    method: "get",
    path: "/projects/{projectId}/fact-check/findings",
    operationId: "listFactCheckFindings",
    summary: "Fact check findings",
    tag: "Fact check",
    scope: "read",
    query: findingsQuery,
    data: arr(
      obj({
        id: str,
        assetId: str,
        assetName: str,
        claim: str,
        verdict: str,
        severity: strN,
        engine: str,
        market: str,
        labelSection: strN,
        labelQuote: strN,
        answerQuote: strN,
        explanation: strN,
        status: str,
        seenCount: int,
        promptText: strN,
        answerId: strN,
        firstSeenAt: str,
        lastSeenAt: str,
      }),
    ),
    meta: { kpis: { type: "object" }, offLabelCount: int, options: { type: "object" }, pagination },
  },
  {
    method: "post",
    path: "/projects/{projectId}/fact-check/run",
    operationId: "runFactCheck",
    summary: "Run fact check",
    description: "Queues a fact-check run for all active assets or one asset (job, 202). Uses the local agent / AI API for judging.",
    tag: "Fact check",
    scope: "write",
    permission: "prompts.manage",
    body: runFactCheckInput,
    status: 202,
    data: obj({ queued: { type: "boolean" }, alreadyRunning: { type: "boolean" }, assetId: strN }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/tasks/{taskId}/status",
    operationId: "setTaskStatus",
    summary: "Set task status",
    description: "open | in_progress | done | dismissed. Connected PM tools / webhooks are notified.",
    tag: "Tasks",
    scope: "write",
    permission: "prompts.manage",
    body: taskStatusInput,
    data: obj({ taskId: str, status: str, changed: { type: "boolean" } }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/tasks/{taskId}/comments",
    operationId: "commentOnTask",
    summary: "Comment on task",
    tag: "Tasks",
    scope: "write",
    permission: "prompts.manage",
    body: taskCommentInput,
    status: 201,
    data: obj({ taskId: str, commented: { type: "boolean" } }),
  },
];
