import "server-only";
import { S, type OpenApiOperation } from "../openapi-helpers";
import { generateReportInput, listReportsQuery, reportDetailQuery, saveReportInput, saveTemplateInput, shareReportInput } from "../reports";

const { str, strN, int, bool, arr, obj } = S;

const urls = { url: str, shareUrl: strN };

const ops: OpenApiOperation[] = [
  {
    method: "get",
    path: "/projects/{projectId}/reports",
    operationId: "listReports",
    summary: "List reports",
    description: "HTML (agent / AI) reports and slide decks, newest first.",
    tag: "Reports",
    scope: "read",
    query: listReportsQuery,
    data: arr(obj({ id: str, kind: str, title: str, subtitle: strN, status: str, aiStatus: str, aiError: strN, slideCount: int, sizeBytes: int, shareEnabled: bool, createdBy: strN, createdAt: str, updatedAt: str, url: str })),
    meta: { total: int, remaining: int, limit: int, offset: int },
  },
  {
    method: "post",
    path: "/projects/{projectId}/reports",
    operationId: "saveReport",
    summary: "Save HTML report",
    description: "Stores a finished self-contained HTML report (open-seo `save_report`). 201 when created; pass reportId to replace one.",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: saveReportInput,
    status: 201,
    data: obj({ reportId: str, title: str, created: bool, htmlBytes: int, ...urls }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/reports/generate",
    operationId: "generateReport",
    summary: "Generate AI report",
    description: "The app's AI writes an HTML report from live project data (job, 202) — poll GET /reports/{reportId} until aiStatus is ready.",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: generateReportInput,
    status: 202,
    data: obj({ reportId: str, status: str, jobId: strN, ...urls }),
  },
  {
    method: "get",
    path: "/projects/{projectId}/reports/{reportId}",
    operationId: "getReport",
    summary: "Get report",
    tag: "Reports",
    scope: "read",
    query: reportDetailQuery,
    data: obj({ id: str, kind: str, title: str, status: str, summary: strN, aiStatus: str, htmlBytes: int, share: { type: "object" }, html: { ...str, description: "Only with includeHtml=true (HTML reports)" }, ...urls }),
  },
  {
    method: "put",
    path: "/projects/{projectId}/reports/{reportId}",
    operationId: "replaceReport",
    summary: "Replace HTML report",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: saveReportInput.omit({ reportId: true }),
    data: obj({ reportId: str, title: str, created: bool, htmlBytes: int, ...urls }),
  },
  {
    method: "delete",
    path: "/projects/{projectId}/reports/{reportId}",
    operationId: "deleteReport",
    summary: "Delete report",
    description: "Permanently deletes the report; its share link stops working.",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    data: obj({ reportId: str, deleted: bool }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/reports/{reportId}/share",
    operationId: "shareReport",
    summary: "Share link",
    description: "Enable / update (password, expiry) / disable the public link, or revoke it permanently (rotates the token).",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: shareReportInput,
    data: obj({ reportId: str, shareEnabled: bool, hasPassword: bool, expiresAt: strN, ...urls }),
  },
  {
    method: "get",
    path: "/projects/{projectId}/report-templates",
    operationId: "listReportTemplates",
    summary: "List report templates",
    tag: "Reports",
    scope: "read",
    data: arr(obj({ id: str, kind: str, name: str, description: strN, instructions: strN, instructionsPreview: str, slideCount: int, updatedAt: str })),
  },
  {
    method: "post",
    path: "/projects/{projectId}/report-templates",
    operationId: "createReportTemplate",
    summary: "Create report template",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: saveTemplateInput.omit({ templateId: true }),
    status: 201,
    data: obj({ templateId: str, name: str, created: bool }),
  },
  {
    method: "put",
    path: "/projects/{projectId}/report-templates/{templateId}",
    operationId: "updateReportTemplate",
    summary: "Update report template",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    body: saveTemplateInput.omit({ templateId: true }),
    data: obj({ templateId: str, name: str, created: bool }),
  },
  {
    method: "delete",
    path: "/projects/{projectId}/report-templates/{templateId}",
    operationId: "deleteReportTemplate",
    summary: "Delete report template",
    tag: "Reports",
    scope: "write",
    permission: "reports.manage",
    data: obj({ templateId: str, deleted: bool }),
  },
];

/** REST v1 operations: reports, share links and templates (reports module). */
export const reportsOperations = ops;
