import "server-only";
import { z } from "zod";
import { LOCAL_TOOL_SCHEMAS } from "@/server/seo";
import type { OpenApiOperation } from "../openapi-helpers";
import {
  addKeywordsBody,
  categoriesQuery,
  createTrackerBody,
  estimateQuery,
  localRunQuery,
  localRunsQuery,
  removeKeywordsBody,
  runCheckBody,
  trackerResultsQuery,
} from "../seo-tracking";

// Local JSON-schema helpers: importing values from ../openapi would be circular (openapi.ts imports this file).
type Json = Record<string, unknown>;
const S = {
  obj: (properties: Json): Json => ({ type: "object", properties }),
  arr: (items: Json): Json => ({ type: "array", items }),
  str: { type: "string" } as Json,
  strN: { type: ["string", "null"] } as Json,
  num: { type: ["number", "null"] } as Json,
  int: { type: "integer" } as Json,
  bool: { type: "boolean" } as Json,
};

const tracker = S.obj({
  trackerId: S.str,
  domain: S.str,
  locationCode: S.int,
  languageCode: S.str,
  locationName: S.strN,
  devices: { type: "string", enum: ["both", "desktop", "mobile"] },
  serpDepth: S.int,
  scheduleInterval: { type: "string", enum: ["manual", "daily", "weekly", "monthly"] },
  nextCheckAt: { type: ["string", "null"], format: "date-time" },
  isActive: S.bool,
  createdAt: { type: "string", format: "date-time" },
  keywordCount: S.int,
  lastRunStatus: S.strN,
  lastRunCompletedAt: { type: ["string", "null"], format: "date-time" },
});
const devicePos = S.obj({ position: S.num, previousPosition: S.num, rankingUrl: S.strN, serpFeatures: S.arr(S.str) });
const localRun = S.obj({
  runId: S.str,
  tool: { type: "string", enum: ["business_search", "local_serp", "rank_grid", "business_profile", "reviews", "questions", "posts"] },
  label: S.str,
  status: { type: "string", enum: ["queued", "running", "processing", "completed", "failed"] },
  error: S.strN,
  costUsd: { type: "number" },
  input: { type: "object" },
  createdAt: { type: "string", format: "date-time" },
  completedAt: { type: ["string", "null"], format: "date-time" },
  result: { type: ["object", "null"], description: "Tool-specific result once completed (DataForSEO fields, snake_case)." },
});
const estimate = S.obj({
  trackerId: S.str,
  costUsd: { type: "number" },
  keywordCount: S.int,
  devicesCount: S.int,
  totalChecks: S.int,
  method: { const: "live" },
  existingKeywordCount: S.int,
  additionalKeywordCount: S.int,
  scheduledEstimate: S.obj({ scheduleInterval: S.str, costUsd: { type: "number" }, checksPerMonth: S.int, monthlyCostUsd: { type: "number" } }),
});

const LOCAL_TOOLS: { slug: string; key: keyof typeof LOCAL_TOOL_SCHEMAS; summary: string; description: string }[] = [
  { slug: "business-search", key: "business_search", summary: "Search local businesses", description: "Google Business listings near a point (~$0.01)." },
  { slug: "local-serp", key: "local_serp", summary: "Local (Maps) SERP", description: "Google Maps / Local Finder results from a point (~$0.002 per 10 results)." },
  { slug: "rank-grid", key: "rank_grid", summary: "Local rank grid", description: "Geo-grid rank of a business (gridSize² Maps checks; 3×3 ≈ $0.036)." },
  { slug: "business-profile", key: "business_profile", summary: "Google Business Profile", description: "Profile details of a business (~$0.005)." },
  { slug: "reviews", key: "reviews", summary: "Google Business reviews", description: "Reviews (asynchronous DataForSEO task; ~$0.0015 per 10)." },
  { slug: "questions", key: "questions", summary: "Google Business Q&A", description: "Questions & answers (~$0.005)." },
  { slug: "posts", key: "posts", summary: "Google Business posts", description: "Posts / updates (asynchronous; ~$0.0015 per 10)." },
];

const localStartBody = (key: keyof typeof LOCAL_TOOL_SCHEMAS) =>
  z.object({
    ...LOCAL_TOOL_SCHEMAS[key].shape,
    waitSeconds: z.number().int().min(0).max(25).default(10).describe("Wait up to N seconds for the result before answering 202."),
  });

type Op = OpenApiOperation;

const operations: Op[] = [
  {
    method: "get",
    path: "/projects/{projectId}/seo/rank-trackers",
    operationId: "listRankTrackers",
    summary: "List rank trackers",
    tag: "Rank tracking",
    scope: "read",
    data: S.arr(tracker),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/rank-trackers",
    operationId: "createRankTracker",
    summary: "Create rank tracker",
    description: "Free — no check runs until POST …/runs or a schedule is due. Defaults: project domain, mobile, depth 40, manual.",
    tag: "Rank tracking",
    scope: "write",
    permission: "seo.run",
    body: createTrackerBody,
    status: 201,
    data: tracker,
  },
  {
    method: "get",
    path: "/projects/{projectId}/seo/rank-trackers/{trackerId}",
    operationId: "getRankTracker",
    summary: "Rank tracker results",
    description: "Current desktop/mobile position per keyword vs. the comparison period, plus the latest run.",
    tag: "Rank tracking",
    scope: "read",
    query: trackerResultsQuery,
    data: S.obj({
      config: tracker,
      comparePeriod: S.str,
      rows: S.arr(
        S.obj({ trackingKeywordId: S.str, keyword: S.str, searchVolume: S.num, keywordDifficulty: S.num, cpc: S.num, desktop: devicePos, mobile: devicePos }),
      ),
      run: { type: ["object", "null"] },
    }),
  },
  {
    method: "delete",
    path: "/projects/{projectId}/seo/rank-trackers/{trackerId}",
    operationId: "archiveRankTracker",
    summary: "Archive rank tracker",
    description: "Stops scheduled checks; history is kept.",
    tag: "Rank tracking",
    scope: "write",
    permission: "seo.run",
    data: tracker,
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/rank-trackers/{trackerId}/keywords",
    operationId: "addRankTrackingKeywords",
    summary: "Add tracked keywords",
    description: "Duplicates are skipped. Scheduled trackers require maxEstimatedScheduledCheckCostUsd (approval of the recurring per-check cost).",
    tag: "Rank tracking",
    scope: "write",
    permission: "seo.run",
    body: addKeywordsBody,
    status: 201,
    data: S.obj({
      trackerId: S.str,
      requested: S.int,
      added: S.int,
      addedIds: S.arr(S.str),
      checkTriggered: S.bool,
      metricsJobId: S.strN,
      scheduledEstimate: { type: "object" },
    }),
  },
  {
    method: "delete",
    path: "/projects/{projectId}/seo/rank-trackers/{trackerId}/keywords",
    operationId: "removeRankTrackingKeywords",
    summary: "Remove tracked keywords",
    description: "JSON body `{ keywordIds }` or query `?keywordIds=a,b`.",
    tag: "Rank tracking",
    scope: "write",
    permission: "seo.run",
    body: removeKeywordsBody,
    data: S.obj({ trackerId: S.str, requested: S.int, removed: S.int, removedIds: S.arr(S.str) }),
  },
  {
    method: "get",
    path: "/projects/{projectId}/seo/rank-trackers/{trackerId}/estimate",
    operationId: "estimateRankTrackerCost",
    summary: "Estimate rank check cost",
    tag: "Rank tracking",
    scope: "read",
    query: estimateQuery,
    data: estimate,
  },
  {
    method: "get",
    path: "/projects/{projectId}/seo/rank-trackers/{trackerId}/runs",
    operationId: "getLatestRankRun",
    summary: "Latest rank check run",
    tag: "Rank tracking",
    scope: "read",
    data: { type: ["object", "null"] },
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/rank-trackers/{trackerId}/runs",
    operationId: "runRankTracker",
    summary: "Run rank check",
    description: "Paid live SERP check (DataForSEO). Refused when the estimate exceeds maxCostUsd; 409 when a run is in progress. Answers 202 — poll GET …/rank-trackers/{trackerId}.",
    tag: "Rank tracking",
    scope: "write",
    permission: "seo.run",
    body: runCheckBody,
    status: 202,
    data: S.obj({ started: S.bool, runId: S.str }),
  },
  ...LOCAL_TOOLS.map(
    (t): Op => ({
      method: "post",
      path: `/projects/{projectId}/seo/local/${t.slug}`,
      operationId: `localSeo_${t.key}`,
      summary: t.summary,
      description: `${t.description} Paid (DataForSEO). Answers 200 with the finished run, or 202 while it is still running — then poll GET …/seo/local/runs/{runId} (free).`,
      tag: "Local SEO",
      scope: "read",
      permission: "seo.run",
      body: localStartBody(t.key),
      data: localRun,
    }),
  ),
  {
    method: "get",
    path: "/projects/{projectId}/seo/local/runs",
    operationId: "listLocalSeoRuns",
    summary: "List local SEO runs",
    tag: "Local SEO",
    scope: "read",
    query: localRunsQuery,
    data: S.arr(S.obj({ runId: S.str, tool: S.str, label: S.str, status: S.str, error: S.strN, costUsd: { type: "number" }, createdAt: S.str, completedAt: S.strN })),
  },
  {
    method: "get",
    path: "/projects/{projectId}/seo/local/runs/{runId}",
    operationId: "getLocalSeoRun",
    summary: "Local SEO run result",
    description: "Free. 202 while the run is still pending; use waitSeconds to long-poll.",
    tag: "Local SEO",
    scope: "read",
    query: localRunQuery,
    data: localRun,
  },
  {
    method: "delete",
    path: "/projects/{projectId}/seo/local/runs/{runId}",
    operationId: "deleteLocalSeoRun",
    summary: "Delete local SEO run",
    tag: "Local SEO",
    scope: "write",
    permission: "seo.run",
    data: S.obj({ runId: S.str, deleted: S.bool }),
  },
  {
    method: "get",
    path: "/projects/{projectId}/seo/local/categories",
    operationId: "listBusinessCategories",
    summary: "Google Business categories",
    description: "Category slugs with business counts (free, cached 7 days; needs DataForSEO credentials on first load).",
    tag: "Local SEO",
    scope: "read",
    query: categoriesQuery,
    data: S.arr(S.obj({ category: S.str, businessCount: S.num })),
    meta: { total: S.int },
  },
];

export const seoTrackingOperations = operations;
