import "server-only";
import type { OpenApiOperation } from "../openapi-helpers";
import {
  backlinksOverviewBody,
  backlinksProfileBody,
  backlinksTopPagesBody,
  domainOverviewBody,
  domainTopPagesBody,
  keywordMetricsBody,
  listSavedKeywordsQuery,
  rankedKeywordsBody,
  referringDomainsBody,
  removeSavedKeywordsBody,
  researchKeywordsBody,
  saveKeywordsBody,
  serpCompetitorsBody,
  serpLocationsQuery,
  serpResultsBody,
  tagSavedKeywordsBody,
} from "../seo-research";

/** REST v1 operations: keyword research, saved keywords, SERP, domain and backlinks (SEO module). */

// Local schema helpers: importing runtime values from ../openapi would create an evaluation cycle
// (openapi.ts imports this file), so only the type is imported.
type Json = Record<string, unknown>;
const obj = (properties: Json, extra: Json = {}) => ({ type: "object", properties, ...extra });
const arr = (items: Json) => ({ type: "array", items });
const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
const str = { type: "string" };
const strN = { type: ["string", "null"] };
const num = { type: ["number", "null"] };
const int = { type: "integer" };
const bool = { type: "boolean" };
const PAID =
  " Paid DataForSEO call (usage is recorded): cached results are free; a cache miss requires the key owner's `seo.run` permission, otherwise 403. 503 `not_configured` when DataForSEO is not set up (Admin → Data Providers).";

const keyword = obj({ keyword: str, searchVolume: num, keywordDifficulty: num, cpc: num, competition: num, intent: strN });
const pageMeta = { totalCount: { type: ["integer", "null"] }, hasMore: bool, page: int, pageSize: int, fetchedAt: str, cached: bool, url: str };

export const seoResearchOperations: OpenApiOperation[] = [
  {
    method: "post",
    path: "/projects/{projectId}/seo/keywords/research",
    operationId: "researchKeywords",
    summary: "Keyword research",
    description: `Keyword ideas for 1–5 seed keywords (researched separately; per-seed ok/error).${PAID}`,
    tag: "SEO · Keywords",
    scope: "read",
    body: researchKeywordsBody,
    data: obj({
      results: arr(
        obj({
          seed: str,
          ok: bool,
          error: str,
          rowCount: int,
          source: str,
          usedFallback: bool,
          cached: bool,
          locationCode: int,
          languageCode: str,
          rows: arr(keyword),
        }),
      ),
      url: str,
    }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/keywords/metrics",
    operationId: "getKeywordMetrics",
    summary: "Keyword metrics",
    description: `Volume, difficulty, CPC, competition, intent and monthly trend for up to 700 keywords (not cached).${PAID}`,
    tag: "SEO · Keywords",
    scope: "read",
    body: keywordMetricsBody,
    data: obj({ locationCode: int, languageCode: str, provider: str, requested: int, keywords: arr(keyword) }),
  },
  {
    method: "get",
    path: "/projects/{projectId}/seo/saved-keywords",
    operationId: "listSavedKeywords",
    summary: "List saved keywords",
    description: "Saved keywords with latest metrics and tags. Free (database only).",
    tag: "SEO · Keywords",
    scope: "read",
    query: listSavedKeywordsQuery,
    data: arr(obj({ id: str, keyword: str, locationCode: int, languageCode: str, searchVolume: num, keywordDifficulty: num, cpc: num, competition: num, intent: strN, tags: arr(str), createdAt: str })),
    meta: { pagination: ref("Pagination"), tags: arr(obj({ id: str, name: str, keywordCount: int })), url: str },
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/saved-keywords",
    operationId: "saveKeywords",
    summary: "Save keywords",
    description:
      "Saves keywords (idempotent) with optional metrics and tags. No DataForSEO call.",
    tag: "SEO · Keywords",
    scope: "write",
    permission: "seo.run",
    body: saveKeywordsBody,
    status: 201,
    data: obj({ savedCount: int, savedKeywordIds: arr(str), requested: int, tags: arr(str), tagMode: str, locationCode: int, languageCode: str, url: str }),
  },
  {
    method: "delete",
    path: "/projects/{projectId}/seo/saved-keywords",
    operationId: "removeSavedKeywords",
    summary: "Remove saved keywords",
    description: "Deletes saved keywords by id (JSON body). Unknown or foreign ids are ignored. Does not affect rank tracking.",
    tag: "SEO · Keywords",
    scope: "write",
    permission: "seo.run",
    body: removeSavedKeywordsBody,
    data: { type: "object" },
  },
  {
    method: "get",
    path: "/projects/{projectId}/seo/saved-keywords/tags",
    operationId: "listSavedKeywordTags",
    summary: "Saved-keyword tags",
    tag: "SEO · Keywords",
    scope: "read",
    data: arr(obj({ id: str, name: str, color: strN, keywordCount: int })),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/saved-keywords/tags",
    operationId: "tagSavedKeywords",
    summary: "Tag saved keywords",
    description: "Adds tags (created if missing) to and/or removes tag ids from saved keywords.",
    tag: "SEO · Keywords",
    scope: "write",
    permission: "seo.run",
    body: tagSavedKeywordsBody,
    data: obj({ taggedCount: int, addedTags: arr(obj({ id: str, name: str })), removedTagIds: arr(str), removedAssignments: int }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/serp",
    operationId: "getSerpResults",
    summary: "Google SERP results",
    description: `Live Google organic results (desktop) for 1–10 keywords at depth 20 or 100 (cached 12h; per-keyword ok/error).${PAID}`,
    tag: "SEO · SERP",
    scope: "read",
    body: serpResultsBody,
    data: obj({
      results: arr(
        obj({
          keyword: str,
          ok: bool,
          error: str,
          depth: int,
          cached: bool,
          items: arr(obj({ rank: int, title: str, url: str, domain: str, description: str, etv: num, referringDomains: num, backlinks: num })),
        }),
      ),
    }),
  },
  {
    method: "get",
    path: "/projects/{projectId}/seo/locations",
    operationId: "searchSerpLocations",
    summary: "Search SERP locations",
    description: "DataForSEO sub-country locations (city, county, region, DMA) by name — free cached registry (needs DataForSEO configured).",
    tag: "SEO · SERP",
    scope: "read",
    query: serpLocationsQuery,
    data: arr(obj({ locationName: str, locationCode: int, locationType: str })),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/domain/overview",
    operationId: "getDomainOverview",
    summary: "Domain overview",
    description: `Estimated organic traffic and ranking keyword count (default: project domain; cached 12h).${PAID}`,
    tag: "SEO · Domain",
    scope: "read",
    body: domainOverviewBody,
    data: obj({ domain: str, displayTarget: str, scope: str, organicTraffic: num, organicKeywords: num, hasData: bool, locationCode: int, languageCode: str, cached: bool, url: str }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/domain/keywords",
    operationId: "getRankedKeywords",
    summary: "Ranked keywords",
    description: `Keywords a domain/URL ranks for, with filters, sorting and pagination (cached 12h per page).${PAID}`,
    tag: "SEO · Domain",
    scope: "read",
    body: rankedKeywordsBody,
    data: obj({
      domain: str,
      ...pageMeta,
      keywords: arr(obj({ keyword: str, position: num, searchVolume: num, traffic: num, cpc: num, keywordDifficulty: num, url: strN, relativeUrl: strN })),
    }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/domain/pages",
    operationId: "getDomainTopPages",
    summary: "Domain top pages",
    description: `Pages with the most organic traffic (cached 12h per page).${PAID}`,
    tag: "SEO · Domain",
    scope: "read",
    body: domainTopPagesBody,
    data: obj({ domain: str, ...pageMeta, pages: arr(obj({ page: str, relativePath: strN, organicTraffic: num, keywords: num })) }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/domain/keyword-suggestions",
    operationId: "getDomainKeywordSuggestions",
    summary: "Domain keyword suggestions",
    description: `Top 100 keywords a domain ranks for by traffic (cached 12h).${PAID}`,
    tag: "SEO · Domain",
    scope: "read",
    body: domainOverviewBody,
    data: obj({ domain: str, keywords: arr(obj({ keyword: str, position: num, searchVolume: num, traffic: num, cpc: num, keywordDifficulty: num })), url: str }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/domain/competitors",
    operationId: "findSerpCompetitors",
    summary: "SERP competitors",
    description: `Domains competing for a set of 1–100 keywords (not cached).${PAID}`,
    tag: "SEO · Domain",
    scope: "read",
    body: serpCompetitorsBody,
    data: obj({ keywords: int, competitors: arr(obj({ domain: str, avgPosition: num, medianPosition: num, visibility: num, etv: num, keywordsCount: num })) }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/backlinks/overview",
    operationId: "getBacklinksOverview",
    summary: "Backlinks overview",
    description: `Backlink summary, 1-year trends and (optionally) the top 100 referring domains (cached 6h).${PAID}`,
    tag: "SEO · Backlinks",
    scope: "read",
    body: backlinksOverviewBody,
    data: obj({
      target: str,
      displayTarget: str,
      scope: str,
      summary: { type: "object" },
      trends: arr({ type: "object" }),
      newLostTrends: arr({ type: "object" }),
      referringDomains: { type: ["object", "null"] },
      cached: bool,
      url: str,
    }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/backlinks/list",
    operationId: "getBacklinksProfile",
    summary: "Backlinks list",
    description: `Paginated backlinks with anchor, link type, ranks, spam score and status (cached 6h).${PAID}`,
    tag: "SEO · Backlinks",
    scope: "read",
    body: backlinksProfileBody,
    data: obj({ target: str, backlinks: obj({ rows: arr({ type: "object" }), totalCount: { type: ["integer", "null"] }, hasMore: bool, page: int, pageSize: int }), cached: bool, url: str }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/backlinks/referring-domains",
    operationId: "getReferringDomains",
    summary: "Referring domains",
    description: `Paginated referring domains (not for subfolder scope; cached 6h).${PAID}`,
    tag: "SEO · Backlinks",
    scope: "read",
    body: referringDomainsBody,
    data: obj({ target: str, referringDomains: obj({ rows: arr({ type: "object" }), totalCount: { type: ["integer", "null"] }, hasMore: bool, page: int, pageSize: int }), cached: bool, url: str }),
  },
  {
    method: "post",
    path: "/projects/{projectId}/seo/backlinks/top-pages",
    operationId: "getBacklinksTopPages",
    summary: "Most linked pages",
    description: `Pages with the most backlinks and referring domains (cached 6h).${PAID}`,
    tag: "SEO · Backlinks",
    scope: "read",
    body: backlinksTopPagesBody,
    data: obj({ target: str, pages: obj({ rows: arr({ type: "object" }), totalCount: { type: ["integer", "null"] }, hasMore: bool, page: int, pageSize: int }), cached: bool, url: str }),
  },
];
